### ISSUE TITLE
Calling the function or defining the mappings in .vimrc doesn't work

### ISSUE THREAD

**Issue by amcsi** [neitanod/vim-clevertab#1]
It only works when I do it myself manually. Not even putting it into after/plugin/myplugins.vim worked.

I am loading the clevertab plugin after ultisnips.

**Comment by gotgenes** [comment]
I ran into the issue.

This is my example VIMRC

``` vim
set nocompatible

set runtimepath+=~/.vim/plugins/repos/github.com/Shougo/dein.vim

" Required:
call dein#begin('~/.vim/plugins')

" Let dein manage dein
call dein#add('Shougo/dein.vim')
call dein#add('Shougo/neocomplete.vim')
call dein#add('SirVer/ultisnips')
call dein#add('honza/vim-snippets')
call dein#add('neitanod/vim-clevertab')
call dein#end()

filetype plugin indent on
syntax enable

if dein#check_install()
  call dein#install()
endif

let g:neocomplete#enable_at_startup = 1

call CleverTab#NeoCompleteFirst()
```

Just as described in #1, the `imap` for `<Tab>` belongs to UltiSnips once this VIMRC has loaded

```
i  <Tab>       * <C-R>=UltiSnips#ExpandSnippet()<CR>
        Last set from ~/shell-configs/.vim/plugins/.dein/autoload/UltiSnips/map_keys.vim
```

If I then manually perform `:call CleverTab#NeoCompleteFirst()`, I get the CleverTab mapping

```
i  <Tab>       * <C-R>=CleverTab#Complete('start')<CR><C-R>=CleverTab#Complete('tab')<CR><C-R>=CleverTab#Complete('ultis
nips')<CR><C-R>=CleverTab#Complete('neocomplete')<CR><C-R>=CleverTab#Complete('keyword')<CR><C-R>=CleverTab#Complete('om
ni')<CR><C-R>=CleverTab#Complete('user')<CR><C-R>=CleverTab#Complete('stop')<CR>
        Last set from ~/shell-configs/.vim/plugins/.dein/autoload/CleverTab.vim
```

Is it possible [this `after` script in UltiSnips](https://github.com/SirVer/ultisnips/blob/master/after/plugin/UltiSnips_after.vim) is the culprit, and if so, maybe you could start a conversation with the UltiSnips maintainers to see if they're willing to bend?

Meanwhile, is setting `g:UltiSnipsExpandTrigger` to something other than `<Tab>` really the workaround here?
